"""empty message

Revision ID: 1f221f61e14d
Revises: 6fa03bbd7b52
Create Date: 2020-03-06 19:34:36.425266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f221f61e14d'
down_revision = '6fa03bbd7b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookedroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('roomId', sa.Integer(), nullable=True),
    sa.Column('bookDate', sa.String(length=20), nullable=False),
    sa.Column('timeId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['roomId'], ['meetingroom.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookedroom')
    # ### end Alembic commands ###
