"""empty message

Revision ID: 21de41f0a456
Revises: 964d5ad6a057
Create Date: 2020-03-04 23:56:10.832549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21de41f0a456'
down_revision = '964d5ad6a057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datetime', sa.Column('index', sa.String(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datetime', 'index')
    # ### end Alembic commands ###
