"""empty message

Revision ID: 5c1aa89ef15f
Revises: 92d6573419f0
Create Date: 2020-02-28 19:46:34.486700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1aa89ef15f'
down_revision = '92d6573419f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roomlevel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roomlevel')
    # ### end Alembic commands ###
