"""empty message

Revision ID: 6fa03bbd7b52
Revises: a1052c264af0
Create Date: 2020-03-05 17:40:17.166192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6fa03bbd7b52'
down_revision = 'a1052c264af0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datetime', sa.Column('endTime', sa.String(length=20), nullable=False))
    op.add_column('datetime', sa.Column('startTime', sa.String(length=20), nullable=False))
    op.drop_column('datetime', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datetime', sa.Column('time', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('datetime', 'startTime')
    op.drop_column('datetime', 'endTime')
    # ### end Alembic commands ###
