"""empty message

Revision ID: 964d5ad6a057
Revises: 5c1aa89ef15f
Create Date: 2020-02-28 21:27:23.741773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964d5ad6a057'
down_revision = '5c1aa89ef15f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookedroom', sa.Column('bookeddate', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookedroom', 'bookeddate')
    # ### end Alembic commands ###
