"""empty message

Revision ID: a1052c264af0
Revises: 21de41f0a456
Create Date: 2020-03-05 16:17:13.829206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1052c264af0'
down_revision = '21de41f0a456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datetime', sa.Column('PreviousId', sa.Integer(), nullable=False))
    op.drop_column('datetime', 'index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datetime', sa.Column('index', mysql.VARCHAR(length=5), nullable=False))
    op.drop_column('datetime', 'PreviousId')
    # ### end Alembic commands ###
